### ISSUE TITLE
new map request to caltopo.com is returning 401 - Authentication Required

### ISSUE THREAD

**Issue by caver456** [ncssar/caltopo_python#6]
Not sure what changed:

```
PS C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python> python test.py
09:09:12 [sartopo_python:1041:INFO] SENDING POST to 'https://caltopo.com/api/v1/acct/11UEE9/CollaborativeMap':
09:09:12 [sartopo_python:1042:INFO] {
   "json": "{\"properties\": {\"mapConfig\": \"{\\\"activeLayers\\\": [[\\\"mbt\\\", 1]]}\", \"cfgLocked\": true, \"title\": \"NewMap\", \"mode\": \"cal\"}, \"state\": {\"type\": \"FeatureCollection\", \"features\": [{\"geometry\": {\"coordinates\": [-120, 39, 0, 0], \"type\": \"Point\"}, \"id\": \"11111111-1111-1111-1111-111111111111\", \"type\": \"Feature\", \"properties\": {\"creator\": \"11UEE9\", \"title\": \"NewMapDummyMarker\", \"class\": \"Marker\"}}]}}",
   "id": ".....",
   "expires": 1718986272888,
   "signature": "....."
}
09:09:12 [sartopo_python:1045:INFO] {'json': '{"properties": {"mapConfig": "{\\"activeLayers\\": [[\\"mbt\\", 1]]}", "cfgLocked": true, "title": "NewMap", "mode": "cal"}, "state": {"type": "FeatureCollection", "features": [{"geometry": {"coordinates": [-120, 39, 0, 0], "type": "Point"}, "id": "11111111-1111-1111-1111-111111111111", "type": "Feature", "properties": {"creator": "11UEE9", "title": "NewMapDummyMarker", "class": "Marker"}}]}}', 'id': '.....', 'expires': 1718986272888, 'signature': '.....'}
09:09:13 [sartopo_python:1096:INFO] response code = 401
09:09:13 [sartopo_python:1124:ERROR] New map request failed:401:{"code":401,"message":"Authentication required","status":"error","timestamp":1718986153477}
09:09:13 [sartopo_python:291:INFO] New map request failed.  See the log for details.
09:09:13 [sartopo_python:2880:CRITICAL] Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\test.py", line 6, in <module>
    sts=SartopoSession('caltopo.com',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 226, in __init__
    raise STSException
sartopo_python.STSException
09:09:13 [sartopo_python:878:INFO] SartopoSession instance deleted for map [NEW].
```

**Comment by caver456** [comment]
Tried all that - still getting 401 Authendication required.  Here's the new transcript:

```
PS C:\Users\caver\Documents\GitHub\caltopo_python> python caltopo_test.py
06:24:26 [caltopo_python:238:INFO] Opening a CaltopoSession object with no associated map.  Use .openMap(<mapID>) later to associate a map with this session.
creating map...
06:24:26 [caltopo_python:284:INFO] about to create a new map with title "newMap" and mode "cal"
06:24:26 [caltopo_python:1340:INFO] {'json': '{"properties": {"mapConfig": {"activeLayers": [["mbt", 1]]}, "title": "newMap", "sharing": "SECRET", "mode": "cal"}, "state": {"type": "FeatureCollection", "features": [{"geometry": {"coordinates": [-120, 39], "type": "Point"}, "type": "Feature", "properties": {"title": "NewMapDummyMarker"}}]}}', 'id': '.....', 'expires': 1750080386345, 'signature': '.....'}
url:https://caltopo.com/api/v1/acct/J54HND/CollaborativeMap
method:post
payload:{
   "properties": {
      "mapConfig": {
         "activeLayers": [
            [
               "mbt",
               1
            ]
         ]
      },
      "title": "newMap",
      "sharing": "SECRET",
      "mode": "cal"
   },
   "state": {
      "type": "FeatureCollection",
      "features": [
         {
            "geometry": {
               "coordinates": [
                  -120,
                  39
               ],
               "type": "Point"
            },
            "type": "Feature",
            "properties": {
               "title": "NewMapDummyMarker"
            }
         }
      ]
   }
}
06:24:26 [caltopo_python:1394:INFO] response code = 401
06:24:26 [caltopo_python:1422:ERROR] New map request failed:401:{"code":401,"message":"Authentication required","status":"error","timestamp":1750080266369}
06:24:26 [caltopo_python:327:INFO] New map request failed.  See the log for details.
r: False
06:24:26 [caltopo_python:1009:INFO] CaltopoSession instance deleted for map [NEW].
```

**Comment by caver456** [comment]
Nope, the sequence isn't it.  This still gives 401:

`body:b'id=...&expires=1750086299156&signature=.....&json=%7B%22properties%22%3A+%7B%22title%22%3A+%22newMap%22%2C+%22mode%22%3A+%22cal%22%2C+%22mapConfig%22%3A+%7B%22activeLayers%22%3A+%5B%5B%22mbt%22%2C+1%5D%5D%7D%2C+%22sharing%22%3A+%22SECRET%22%7D%2C+%22state%22%3A+%7B%22type%22%3A+%22FeatureCollection%22%2C+%22features%22%3A+%5B%7B%22type%22%3A+%22Feature%22%2C+%22geometry%22%3A+%7B%22type%22%3A+%22Point%22%2C+%22coordinates%22%3A+%5B-120%2C+39%5D%7D%2C+%22properties%22%3A+%7B%22title%22%3A+%22NewMapDummyMarker%22%7D%7D%5D%7D%7D'`
